coreos/butane

- base/v0_1/schema.go
- base/v0_1/translate.go
- base/v0_1/translate_test.go
- base/v0_1/validate.go
- base/v0_1/validate_test.go
- go.mod
Add a field storage.files.contents.inline in addition to the existing
"source" field. "inline" is mutually exclusive with "source".
> base: add sugar for inlining files

- build
This isn't needed and breaks without cgo enabled.
> build: don't use -buildmode=pie

- docs/getting-started.md
The detached sig file needs to come first in the latest version of `gpg`
> Fix gpg verification command in docs

- internal/main.go
This will let you actually write an ignition file with the `--output` flag.
Also added a newline print to the error printing function.
> main: Fix output file handling

- docs/getting-started.md
Closes #13
Add quick instructions on how to import CoreOS application public key (just in case)
> Docs: Update gpg verify instructions

- docs/getting-started.md
We publish fcct containers on quay. Document that and add instructions.
Fixes https://github.com/coreos/fcct/issues/19
> docs/getting-started: add fcct container docs

- docs/getting-started.md
Very minor nit while going through the guide - see commit message.
> docs/getting-started: document absolute path for config bind mount

- internal/main.go
Ensure we're not just overwriting the first bit of the file but rather
are replacing it.
fixes https://github.com/coreos/fcct/issues/42
> main: use O_TRUNC when opening output file

- docs/getting-started.md
As said in the [libpod doc](https://github.com/containers/libpod/blob/master/docs/podman-run.1.md)
> NOTE: The -t option is incompatible with a redirection of the podman client standard input.
If you leave the ```-t``` flag your_config.fcc content is sent to stdout and the prompt is waiting endlessly.
> docs/getting-started.md: removed -t flag for podman run using stdin

- config/config.go
- config/v1_0/fcos.go
- docs/configuration-v1_0.md
- internal/main.go
Two small fixes.
Fixes https://github.com/coreos/fcct/issues/47
Fixes https://github.com/coreos/fcct/issues/45
> Print to stderr, document inline file contents

- base/v0_1/translate.go
- base/v0_1/translate_test.go
- config/common/common.go
- config/common/common_test.go
- config/v1_0/fcos.go
- distro/fcos/v0_1/translate.go
- go.mod
- translate/tests/pkga/types.go
- translate/tests/pkgb/types.go
- translate/tests/readme.txt
- translate/translate.go
- translate/translate_test.go
In this PR:
- Fork Ignition's translation code - we need to do more complex things than it ever did
- Update the translation code to also emit a list of (src, dest) paths. For example you might have (`$yaml.storage.files.4.contents.inline`, `$json.storage.files.4.contents.source`) meaning the 5th element of the files in the generating config got it's source field from the corresponding inline field in the fcc. 
- Use that list of translations to convert a report with ignition paths to fcc paths, then correlate that to the actual source for line/col information.
- Add a bunch of helpers to make writing translators for that easier
- Update tests for handle all this and test the new functionality
> Fix line and column handling and propagation

- base/v0_2_exp/schema.go
- base/v0_2_exp/translate.go
- base/v0_2_exp/translate_test.go
- base/v0_2_exp/validate.go
- base/v0_2_exp/validate_test.go
- config/config.go
- config/v1_1_exp/fcos.go
- distro/fcos/v0_1/translate.go
- docs/configuration-v1_1-exp.md
Add the experimental spec where development can take place. The v1.0 spec is frozen.
Fixes https://github.com/coreos/fcct/issues/51
> Add spec 1.1.0-experimental

- .github/ISSUE_TEMPLATE/release-checklist.md
- docs/getting-started.md
Don't expect users to know the version number of the current release.
Fixes #63.
> {docs,release-checklist}: add Quay tag pointing to latest release

- docs/getting-started.md
- internal/main.go
Accept input filename as bare argument rather than requiring the `--input` option.  Continue accepting `--input` but hide it from `--help`.
Also, fail if we receive extra command-line arguments.
Fixes #69.  Depends on #70.
> main: accept input filename as bare argument; deprecate --input

- docs/configuration-v1_0.md
- docs/configuration-v1_1-exp.md
It's possible to append inline contents but this wasn't documented.
> docs: document inline property on files[].append[]

- internal/main.go
Add a final newline to output, both with and without `--pretty`, to match Unix convention.
> main: append newline to output

- config/v1_0/fcos.go
- config/v1_1_exp/fcos.go
This unifies the final validation step on the generated JSON config,
adding a duplicate check on keys which was previously missing and
only performed by Ignition.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/451
> config/common: validate duplicate keys

- base/v0_2_exp/translate.go
Any mount options that should be applied by Ignition are probably relevant in the real root too.  If we're asked to generate a mount unit, copy them over.
> base/v0_2: include mount options in generated mount unit

- base/options.go
- base/v0_2/translate.go
- base/v0_2/translate_test.go
- base/v0_3_exp/translate.go
- base/v0_3_exp/translate_test.go
Fixes: https://github.com/coreos/fcct/issues/123
If this is agreeable, can we also port it back to v0.2?
> base: Make gzip auto-compression skipable

- docs/examples.md
- Includes shared link for password-hashes
- Updates references for `password_hash` to go to RH Knowledge Base
- RH Knowledge Base article covers all supported password schemes
I found myself having to dig through documentation around this since it wasn't referenced here. I figure that the Red Hat Knowledge Base is a fair reference, and it covers all supported hash functions, the format of the hash string, and more. This was useful for me while I was setting up some FCC files, figured I'd contribute it back up for anyone else who might need it.
Let me know if there's anything else I should include.
> Password Hashing Documentation Updates

- .github/ISSUE_TEMPLATE/release-checklist.md
This will update the release instructions to provide some information around the `master` branch reference and clarify the step while publishing a release.
> release-checklist: update tagging and GitHub release instructions

- base/util/file.go
- base/util/test.go
- base/util/url.go
- base/v0_1/translate_test.go
- base/v0_2/translate.go
- base/v0_2/translate_test.go
- base/v0_2/validate_test.go
- base/v0_3/translate.go
- base/v0_3/translate_test.go
- base/v0_3/validate_test.go
- base/v0_4_exp/translate.go
- base/v0_4_exp/translate_test.go
- base/v0_4_exp/validate_test.go
Stop copying spec-independent utility code every time we stabilize a base package.  Each of these functions is potentially useful to outside code, so put them in a `util` package rather than `internal`.
> base: Move spec-independent code to a utility package

- base/util/test.go
- base/v0_1/translate_test.go
- base/v0_1/validate_test.go
- base/v0_2/translate_test.go
- base/v0_2/validate_test.go
- base/v0_3/translate_test.go
- base/v0_3/validate_test.go
- base/v0_4_exp/translate_test.go
- base/v0_4_exp/validate_test.go
It's easier when writing tests and produces nicer output.
> base/*: consistently use testify

- base/util/file.go
- base/util/file_test.go
- base/v0_1/validate.go
- base/v0_1/validate_test.go
- base/v0_2/validate.go
- base/v0_2/validate_test.go
- base/v0_3/validate.go
- base/v0_3/validate_test.go
- base/v0_4_exp/validate.go
- base/v0_4_exp/validate_test.go
- config/common/errors.go
Users sometimes forget to write file/directory modes with a leading zero and end up with a nonsensical configuration.  If a specified mode is unreasonable but would have been reasonable if it had been written in octal, report a warning.  Apply to all spec versions because it's just a warning.
Closes #131.
> base: warn if file/dir modes appear to have been specified in decimal

- base/util/merge.go
- base/util/merge_test.go
- go.mod
- go.sum
- vendor/github.com/coreos/ignition/v2/config/merge/merge.go
- vendor/github.com/coreos/ignition/v2/config/util/parsingErrors.go
- vendor/modules.txt
We can use this to implement desugaring by generating a separate desugared config and merging it with the translated one.
> base/util: add function to merge configs and TranslationSets

- config/common/errors.go
- config/config.go
- config/fcos/v1_3_exp/schema.go
- config/fcos/v1_3_exp/translate.go
- config/fcos/v1_3_exp/translate_test.go
- config/fcos/v1_3_exp/validate.go
- config/fcos/v1_3_exp/validate_test.go
- docs/configuration-v1_3-exp.md
- docs/specs.md
- go.mod
- go.sum
- vendor/github.com/coreos/ignition/v2/config/merge/merge.go
- vendor/modules.txt
Add sugar for mirroring the root disk (all partitions) and/or encrypting the root partition.  Design document in https://github.com/coreos/enhancements/pull/3.
Example FCC:
```yaml
variant: fcos
version: 1.3.0-experimental
boot_device:
layout: x86_64
mirror:
devices:
- /dev/vda
- /dev/vdb
luks:
tang:
- url: https://example.com/
thumbprint: x
tpm2: true
threshold: 2
```
> Add boot_device sugar

- config/config.go
- config/rhcos/v0_1/schema.go
- config/rhcos/v0_1/translate.go
- config/rhcos/v0_2_exp/schema.go
- config/rhcos/v0_2_exp/translate.go
- docs/config-fcos-v1_0.md
- docs/config-fcos-v1_1.md
- docs/config-fcos-v1_2.md
- docs/config-fcos-v1_3.md
- docs/config-fcos-v1_4-exp.md
- docs/config-rhcos-v0_1.md
- docs/config-rhcos-v0_2-exp.md
- docs/specs.md
Add an `rhcos` variant with `version` `0.1.0` as an alias for `fcos` `1.3.0`, and an `0.2.0-experimental` spec as an alias for `fcos 1.4.0-experimental`.  Specialize spec docs to handle each variant/version pair independently.
The idea behind `0.1.0` is to get this spec released in a usable form and gain some experience with RHCOS users using it.  We might then want to add RHCOS-specific validation, which would further restrict the set of valid configs and thus be a breaking change.  That development would eventually be stabilized as a `1.0.0` spec.
> config: add rhcos 0.1.0 and 0.2.0-experimental variants

- docs/config-fcos-v1_0.md
- docs/config-fcos-v1_1.md
- docs/config-fcos-v1_2.md
- docs/config-fcos-v1_3.md
- docs/config-fcos-v1_4-exp.md
- docs/config-rhcos-v0_1.md
- docs/config-rhcos-v0_2-exp.md
It's not required unless files are being written into the filesystem.
> docs: make storage.filesystems.path field optional

- README.md
- docs/development.md
The layout docs are relevant to developers and folks wanting to use FCCT as a library, but not to users, and they're currently taking up most of the GitHub front page.  Move them to dev docs, where they'll also show up in GitHub Pages.
> README: move project layout section to dev docs

- test
`go run` builds the program from source each time.  Instead, have `./test` run `./build` once and then use the resulting `fcct` binary.
Reduces `./test` time from ~16 seconds to ~1.4 seconds on my system.
> test: don't recompile fcct for every FCC in docs

- Dockerfile
- build_for_container
We don't use them in the resulting container.
Also rename `build_releases` to clarify that it's only used for the container build now.
Fixes https://github.com/coreos/fcct/issues/151.
> Stop building non-Linux-x86_64 binaries during container build

- docs/getting-started.md
This places the container option first, Fedora package second and the binaries last, similarly to how this is organised in FCOS tutorial docs: https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-setup/
> docs: Update fcct download instructions

- config/fcos/v1_3/translate.go
- config/fcos/v1_4_exp/translate.go
When the boot_device mirror functionality was added we added
`ToIgn3_XUnvalidated` functions to the `fcos` `v1_3` & `v1_4_exp`
configs which were not checking that the base configs were valid before
attempting to merge in child configs. Add a quick check that the report
for the base config is not fatal before continuing.
Fixes #192
> config/fcos: Avoid merging invalid configs

- docs/migrating-configs.md
The example there doesn't work as one would expect: it actually creates
a new partition labeled `root` with the given size. We need to pin it
using the partition number to make sure it affects the existing one.
> docs: fix `resize` example

- config/common/common.go
- config/fcos/v1_0/validate_test.go
- config/fcos/v1_1/validate_test.go
- config/fcos/v1_2/validate_test.go
- config/fcos/v1_4_exp/validate_test.go
- config/util/util.go
- go.mod
- go.sum
- internal/main.go
- test
- translate/set.go
- translate/translate.go
- vendor/github.com/coreos/ignition/v2/config/merge/merge.go
- vendor/github.com/coreos/ignition/v2/config/shared/errors/errors.go
- vendor/github.com/coreos/ignition/v2/config/v3_0/types/filesystem.go
- vendor/github.com/coreos/ignition/v2/config/v3_0/types/partition.go
- vendor/github.com/coreos/ignition/v2/config/v3_1/types/filesystem.go
- vendor/github.com/coreos/ignition/v2/config/v3_1/types/partition.go
- vendor/github.com/coreos/ignition/v2/config/v3_2/types/filesystem.go
- vendor/github.com/coreos/ignition/v2/config/v3_2/types/partition.go
- vendor/github.com/coreos/ignition/v2/config/v3_3_experimental/types/filesystem.go
- vendor/github.com/coreos/ignition/v2/config/v3_3_experimental/types/partition.go
- vendor/modules.txt
The consequences of an incorrect TranslationSet are subtle, since it only affects line/column correlation in Report entries.  Add some correlation tests and a hidden debug option to report the final set of translations.
> Improve TranslationSet observability, add some tests

- config/common/common.go
- config/common/errors.go
- config/config.go
- config/openshift/v4_8_exp/result/schema.go
- config/openshift/v4_8_exp/schema.go
- config/openshift/v4_8_exp/translate.go
- config/openshift/v4_8_exp/validate.go
- config/openshift/v4_8_exp/validate_test.go
- config/util/util.go
- docs/config-openshift-v4_8-exp.md
- docs/specs.md
- internal/main.go
- translate/set.go
- translate/util.go
Rename `rhcos`/`0.2.0-experimental` to `openshift`/`4.8.0-experimental`.  Use `openshift` as the variant name instead of `rhcos` because RHCOS is an implementation detail of OpenShift, and also would leave OKD in an awkward position.  By reusing OpenShift version numbers, we're setting ourselves up to eventually violate semver, but it doesn't seem reasonable to create a novel set of user-facing version numbers that isn't connected to anything else.
Have the new spec generate MachineConfigs by default, but also accept a new `-r/--raw/Raw` option to generate an Ignition config.  This allows FCCT to be used for sugar (e.g. for [boot disk mirroring](https://docs.openshift.com/container-platform/4.7/installing/install_config/installing-customizing.html#installation-special-config-mirrored-disk_ …
> Add openshift/4.8.0-exp that produces MachineConfigs by default

- config/common/errors.go
- config/openshift/v4_8_exp/schema.go
- config/openshift/v4_8_exp/validate.go
- config/openshift/v4_8_exp/validate_test.go
- docs/config-openshift-v4_8-exp.md
Require a non-empty `machineconfiguration.openshift.io/role` label in `metadata.labels`.
Addresses https://github.com/coreos/fcct/pull/214#issuecomment-802960498.  cc @sinnykumari
> openshift/v4_8_exp: require machineconfiguration.openshift.io/role

- config/common/errors.go
- config/openshift/v4_8_exp/result/schema.go
- config/openshift/v4_8_exp/schema.go
- config/openshift/v4_8_exp/translate.go
- config/openshift/v4_8_exp/translate_test.go
- config/openshift/v4_8_exp/validate.go
- config/openshift/v4_8_exp/validate_test.go
- config/util/util.go
- config/util/util_test.go
- docs/config-openshift-v4_8-exp.md
- translate/set.go
- translate/util.go
Add an `openshift` section containing the fields at the top level of a MachineConfig:
```yaml
variant: openshift
version: 4.8.0-experimental
metadata:
name: z
openshift:
kernel_arguments: [a, b, c]
extensions: [d, e]
fips: true
kernel_type: realtime
```
Output:
```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
name: z
spec:
config:
ignition:
version: 3.2.0
extensions:
- d
- e
fips: true
kernelArguments:
- a
- b
- c
kernelType: realtime
```
Report warnings in `--raw` mode if any such fields are specified, since we can't represent them directly in an Ignition config.
Followup to #212.
cc @sinnykumari
> openshift/v4_8_exp: support top-level MachineConfig fields

- base/v0_1/translate.go
- base/v0_2/translate.go
- base/v0_3/translate.go
- base/v0_4_exp/translate.go
- translate/set.go
- translate/translate_test.go
`AddIdentity()` doesn't know the field contents, so it can't skip adding a translation if the field is nil.  Switch to translating all fields via `translate.MergeP()`, rather than assigning directly and calling `AddIdentity()` afterward.  `MergeP()` is a better affordance than we had when `AddIdentity()` was introduced in 23146d3.
Delete `AddIdentity()` to remove the footgun.  This is an API break, but probably there are no out-of-tree callers.
> base/*: use MergeP() everywhere; drop AddIdentity()

- config/openshift/v4_8_exp/result/schema.go
- config/openshift/v4_8_exp/translate.go
- config/openshift/v4_8_exp/translate_test.go
If `openshift.fips` is specified, add `--cipher aes-cbc-essiv:sha256` to `storage.luks.*.options` unless a cipher is already specified in the options list.  The default cipher uses XTS, which isn't allowed by FIPS 140-2.
Fixes #198.  We key off of the `openshift.fips` field, rather than creating a new field shared with FCOS, since the former already exists and FCOS isn't likely to support FIPS.
> openshift/v4_8_exp: set cipher for LUKS volumes if FIPS enabled

- config/util/util.go
If we found a translation, the YAML side will already be in snake case, so skip the snake-casing for clarity.  This shouldn't change any behavior.
It'd be nice to remove the missing-translation fallback, but it's still used in some cases, so add a comment with some context.
> config/util: only convert paths to snake case as a fallback

- docs/config-openshift-v4_8.md
- docs/config-openshift-v4_9-exp.md
- docs/development.md
- docs/specs.md
- docs/upgrading-fcos.md
- docs/upgrading-openshift.md
- docs/upgrading.md
Also drop unsupported fields from `openshift` spec docs and update a couple field descriptions.
Demo site available [here](https://bgilbert.github.io/butane/).
Requires https://github.com/coreos/coreos.github.io/pull/3.
> docs: provide separate upgrade docs for each variant; add OpenShift upgrade guide

- .github/workflows/container.yml
Rootless Podman is broken in GitHub Actions Ubuntu 20.04 20210419.1.
https://github.com/actions/virtual-environments/issues/3229
> workflows: work around podman build breakage

- .github/workflows/container.yml
We can revert the workaround once https://github.com/actions/virtual-environments/issues/3229 is fixed (and thus CI is green for this PR).
This reverts https://github.com/coreos/butane/pull/235.
> Revert "workflows: work around podman build breakage"

- Dockerfile
Avoid build failures due to Docker Hub rate limits.
> Dockerfile: build container using Fedora

- go.mod
Ignition requires it, and we don't test anything older in CI.
xref https://github.com/coreos/ignition/pull/1225
> go.mod: bump Go to 1.13

- .github/ISSUE_TEMPLATE/release-checklist.md
Requires https://github.com/coreos/coreos-assembler/pull/2246.
> templates: vendor new Butane releases into mantle

- docs/specs.md
This clarifies that they should not be used and that they will be
removed in a future major release.
> docs: Split deprecated spec versions from stable ones

- base/v0_4/translate.go
- base/v0_4/translate_test.go
- base/v0_5_exp/translate.go
- base/v0_5_exp/translate_test.go
- config/common/errors.go
- config/openshift/v4_9_exp/translate.go
- config/openshift/v4_9_exp/translate_test.go
- docs/config-fcos-v1_4-exp.md
- docs/config-openshift-v4_9-exp.md
The MCC in OCP 4.9 is unable to parse Ignition 3.3.0 configs that are not also valid 3.2.0 configs.  Reject affected fields.
In addition, we don't want to expose `KernelArguments` in two different places that have different semantics. Document that we want to reject the Ignition `KernelArguments` fields to encourage the use of the MCO's related field, as it will also affect subsequent boots.
Closes #237.
> openshift/4.9: forbid Ignition spec 3.3.0 fields rejected by MCC

- .github/ISSUE_TEMPLATE/release-checklist.md
These are not strictly part of the upstream release, but let's keep the entire process in one place so nothing gets missed.
> templates: add some external tasks to the release checklist

- .github/workflows/container.yml
- .github/workflows/go.yml
- go.mod
- vendor/modules.txt
F33, F34, and OCP 4.9 have Go 1.15 or higher.
> Drop EOL Go versions, bump linter, restrict workflow access to repo

- go.mod
- go.sum
- internal/main.go
- vendor/github.com/spf13/pflag/flag.go
- vendor/github.com/spf13/pflag/ip.go
- vendor/github.com/spf13/pflag/ipnet_slice.go
- vendor/github.com/spf13/pflag/string_array.go
- vendor/modules.txt
Since the user is explicitly requesting help, print it to stdout for ease of piping.
Fixes #267.
> main: send `--help` output to stdout

- config/openshift/v4_9/result/schema.go
- config/openshift/v4_9/schema.go
- config/openshift/v4_9/translate.go
- config/openshift/v4_9/translate_test.go
- docs/config-openshift-v4_9.md
- docs/specs.md
The MCO PR (https://github.com/openshift/machine-config-operator/pull/2675) to support spec 3.3.0 in OpenShift 4.9 didn't land in time.  Revert `openshift`/`4.9.0` to spec 3.2.0.
This is a semver violation for the `openshift`/`4.9.0` spec, which is unfortunate.  However, it doesn't break existing configs, because we already reject configs that use any new features from 3.3.0.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1989454
> openshift/v4_9: roll back to Ignition spec 3.2.0

- config/fcos/v1_3/translate.go
- config/fcos/v1_3/translate_test.go
- config/fcos/v1_4/translate.go
- config/fcos/v1_4/translate_test.go
- config/fcos/v1_5_exp/translate.go
- config/fcos/v1_5_exp/translate_test.go
On aarch64 and ppc64le, FCOS and RHCOS have added reserved partitions to keep partition numbers consistent between arches.  Add those partitions to the boot device mirror templates, including in stable specs.  This shouldn't introduce compatibility problems: transposefs in older OS releases will ignore the reserved partitions, any configs relying on partition numbers should be specifying them explicitly, and in any event this only affects secondary arches.
Details in https://github.com/coreos/fedora-coreos-tracker/issues/855.
> config/fcos/*: add reserved partitions on aarch64/ppc64le

- config/common/errors.go
- config/rhcos/v0_1/translate.go
#256 marked the `rhcos` variant deprecated, but we're still seeing folks try to use it in new applications.  Add a warning when the variant is used.
> rhcos: add deprecation warning

- .github/ISSUE_TEMPLATE/release-checklist.md
No need to vendor the new Butane version in mantle after [this](https://github.com/coreos/coreos-assembler/pull/2529) PR
> templates: skip vendoring the new version in favor of dependabot

- go.mod
- go.sum
- vendor/github.com/vincent-petithory/dataurl/dataurl.go
- vendor/modules.txt
There's a tagged release now; let's use it.
> go.mod: update dataurl to 1.0.0

- config/common/errors.go
- config/fcos/v1_3/translate.go
- config/fcos/v1_3/translate_test.go
- config/fcos/v1_4/translate.go
- config/fcos/v1_4/translate_test.go
- config/fcos/v1_5_exp/translate.go
- config/fcos/v1_5_exp/translate_test.go
Fixes https://github.com/coreos/butane/issues/243
This change warns if the partition number for the `root` label is not specified or wrongly mentioned.
> config/fcos: warn if the partition number for root isn't correct

- docs/config-fcos-v1_0.md
- docs/config-fcos-v1_1.md
- docs/config-fcos-v1_2.md
- docs/config-fcos-v1_3.md
- docs/config-fcos-v1_4.md
- docs/config-fcos-v1_5-exp.md
- docs/config-openshift-v4_10-exp.md
- docs/config-openshift-v4_8.md
- docs/config-openshift-v4_9.md
- docs/config-rhcos-v0_1.md
It's mandatory for Ignition configs, but optional for Butane configs.
Reported by @Nemric.
> docs/config-*: ignition section is optional

- config/openshift/v4_10_exp/translate.go
- config/openshift/v4_10_exp/translate_test.go
https://github.com/openshift/machine-config-operator/pull/2820 adds file compression support to the MCO.  Allow it to be enabled in a config, either explicitly or automatically.
This reverts 023fdd41adbb and part of e29e373b4645 for 4.10.0-exp.
> openshift/v4_10_exp: re-enable file compression

- docs/getting-started.md
Using '--tty' conflicts with stdin redirection:
https://docs.podman.io/en/latest/markdown/podman-run.1.html#tty-t
> docs: Don't use '--tty-' for butane alias

- config/common/errors.go
- config/openshift/v4_10_exp/translate.go
- config/openshift/v4_10_exp/translate_test.go
- config/openshift/v4_8/translate.go
- config/openshift/v4_8/translate_test.go
- config/openshift/v4_9/translate.go
- config/openshift/v4_9/translate_test.go
- docs/config-openshift-v4_10-exp.md
- docs/config-openshift-v4_8.md
- docs/config-openshift-v4_9.md
The MCO fails on a parse error when attempting to reconcile a file sourced from a URL scheme other than `data`.  Reject such URLs, including in stable specs.
Drop `http_headers` from the spec docs, since it doesn't make sense for data URLs.  Ignition config validation already rejects the field in this case.
cc @yuqi-zhang to confirm that this is the right thing to do.
> openshift/*: reject `storage.files.contents.source` with non-`data` URL

- docs/config-fcos-v1_1.md
- docs/config-fcos-v1_2.md
- docs/config-fcos-v1_3.md
- docs/config-fcos-v1_4.md
- docs/config-fcos-v1_5-exp.md
- docs/config-openshift-v4_10.md
- docs/config-openshift-v4_11-exp.md
- docs/config-openshift-v4_8.md
- docs/config-openshift-v4_9.md
- docs/config-rhcos-v0_1.md
`openshift` 4.8.0 and 4.9.0 don't support it at all.  All other specs, except `fcos` 1.0.0, support it in config merge/replace and certificate authorities.
> Fix spec docs for `compression` field

- config/openshift/v4_10/result/schema.go
- config/openshift/v4_10/schema.go
- config/openshift/v4_10/translate.go
- config/openshift/v4_10/translate_test.go
- docs/config-openshift-v4_10.md
- docs/specs.md
The MCO doesn't support 3.3.0 yet, so we need to roll back `openshift` 4.10.0 to `fcos` 1.3.0 and base 0.3.  Validation was already rejecting the new fields in 3.3.0, so there are no docs changes to revert.
See also #269.
> openshift/v4_10: roll back to Ignition spec 3.2.0

- README.md
- docs/development.md
As visible in #87: it's not very straight forward to understand where and how the final binaries offered here are built.
> docs: add information about the build system

- config/common/errors.go
- config/fcos/v1_5_exp/schema.go
- config/fcos/v1_5_exp/translate.go
- config/fcos/v1_5_exp/translate_test.go
- config/fcos/v1_5_exp/validate.go
- config/fcos/v1_5_exp/validate_test.go
- docs/config-fcos-v1_5-exp.md
- docs/config-openshift-v4_11-exp.md
Use []struct: https://github.com/coreos/butane/pull/304#discussion_r791945381
> config/fcos/v1_5_exp: use array of extension instead of string

- docs/development.md
As discussed in and evident from
https://src.fedoraproject.org/rpms/butane/pull-request/5 the PR process
for non-packagers is not exactly obvious and requires additional local
setup to work.
> docs: add information on PRs for the build process

- config/fcos/v1_0/translate.go
- config/fcos/v1_0/translate_test.go
- config/fcos/v1_1/translate.go
- config/fcos/v1_1/translate_test.go
- config/fcos/v1_2/translate.go
- config/fcos/v1_2/translate_test.go
Ideally, this change should have been addressed for `fcos v1_0, v1_1, and v1_2` in #279, however, it's missed somehow.
> backport #279 to fcos < 1.3

- .github/ISSUE_TEMPLATE/release-checklist.md
The new releng signing script gets all binaries from the `-redistributable` subpackage, uses the F35 key, and can skip the sigul run if requested by an environment variable.
The new ART sync ticket drops one-time introductory language.
> templates/release-checklist: update example ticket links

- NEWS
We're now statically linking the Linux release binaries.  That change wasn't strictly in this repo, but it's user-visible.
> NEWS: add missing entry for 0.14.0

- .gitattributes
- .github/workflows/go.yml
- base/v0_2/translate.go
- base/v0_2/translate_test.go
- base/v0_3/translate.go
- base/v0_3/translate_test.go
- base/v0_4/translate.go
- base/v0_4/translate_test.go
- base/v0_5_exp/translate.go
- base/v0_5_exp/translate_test.go
- build
- test
We build releases on those platforms, so let's check them in CI.  To reduce CI resources, only check with the latest Go version, and skip linting.  Disable individual checks in `./test` on platforms where they can't be easily supported.
Also fix path separator confusion on Windows, affecting trees and `Resource.Local`, and fix or disable broken tests.
> Add CI on macOS and Windows; fix Windows path handling and tests

- .copr/Makefile
I'd like to enable auto-builds of this repo to
https://copr.fedorainfracloud.org/coprs/g/CoreOS/continuous/ so it could
eventually feed into
https://github.com/coreos/fedora-coreos-tracker/issues/910.
> Add COPR integration Makefile

- docs/examples.md
RHEL 8 ships a different implementation of `mkpasswd` that doesn't support modern hashes.  For ease of use, just containerize `mkpasswd`.
> docs/examples: use `mkpasswd` container

- .github/workflows/go.yml
Expanded the list of OS used to include mac + windows; flipped the
logic to exclude combinations of go + mac/windows we don't want to
test.
> ci: add testing using go 1.18

- .github/workflows/container.yml
- Dockerfile
- build_for_container
Quay builds are amd64-only and haven't been especially reliable.  Use GitHub Actions to build both amd64 and arm64 containers for the main branch and for tags, and push them to Quay.  Continue building but not pushing containers on PR.  Requires the `QUAY_AUTH` repo secret to be set to a Docker credential.
Ideally we would cross-build the arm64 container by having the Dockerfile specify `FROM --platform=$BUILDPLATFORM` for the builder container and set `GOARCH=$TARGETARCH`.  However, Buildah < 1.24.1 doesn't support `--platform` in `FROM`.  Build in emulation for now, and skip arm64 in PRs to speed up CI.
Fixes https://github.com/coreos/butane/issues/324.  Alternative to #325.
> workflows: build and push container from GitHub Actions

- config/common/errors.go
- config/config.go
- config/flatcar/v1_0/schema.go
- config/flatcar/v1_0/translate.go
- config/flatcar/v1_0/translate_test.go
- config/flatcar/v1_1_exp/schema.go
- config/flatcar/v1_1_exp/translate.go
- config/flatcar/v1_1_exp/translate_test.go
- docs/config-flatcar-v1_0.md
- docs/config-flatcar-v1_1-exp.md
- docs/config-openshift-v4_10.md
- docs/config-openshift-v4_11-exp.md
- docs/config-openshift-v4_8.md
- docs/config-openshift-v4_9.md
- docs/config-rhcos-v0_1.md
- docs/specs.md
Hi,
With the latest Alpha release of Flatcar (3185.0.0), Ignition version has been updated to 2.13.0. Besides Ignition v1 and v2 configurations, Ignition configurations with specification v3 (up to 3.3.0) are now supported.
This PR brings a `flatcar` butane variant to generate Ignition spec to version `3.3.0`.
> config: add `flatcar` variant

- Dockerfile
I'm trying to use butane in a `Dockerfile` as part of a multi-stage
build, and not having anything except the binary in the container
breaks that since `Dockerfile` wants to invoke things via `/bin/sh`.
Use ubi8 as a base.
> Dockerfile: Use a full base image

- config/common/errors.go
- config/openshift/v4_10/translate.go
- config/openshift/v4_10/translate_test.go
- config/openshift/v4_10/validate_test.go
- config/openshift/v4_11_exp/translate.go
- config/openshift/v4_11_exp/translate_test.go
- config/openshift/v4_11_exp/validate_test.go
MCO 4.10+ rejects file modes larger than 0777.  Add a validation to do that too.  In versions older than 4.10, both Ignition and the MCO ignore special mode bits, so we also continue doing so to avoid breaking previously-working configs.  (There's nothing preventing users from using an older Butane spec with a newer OpenShift, but the missed validation in that case seems reasonable to avoid the breaking change.)
Change the `ErrDecimalMode` test to avoid accidentally triggering `ErrFileSpecialModeSupport` as well.
> config/openshift: reject file modes with special bits set

- translate/set.go
- translate/set_test.go
- translate/translate_test.go
In special circumstances, postprocessing code may need to rearrange fields already translated to output space, in which case it needs to update the corresponding translations.  Provide a helper function to do so.
For https://github.com/coreos/butane/pull/339.
> translate: add `TranslationSet.Map()` to further translate `To` fields

- go.mod
- go.sum
- vendor/modules.txt
This is a no-op here, but let's be consistent with Ignition.
> go.mod: update to current vcontext

- translate/set.go
- translate/set_test.go
`AddFromCommonSource` was using the `ToTag` in both paths.  Use the `FromTag` in the `From` path, and add a test.
Followup to #339.
> translate: use `FromTag` in `From` paths added by `AddFromCommonSource`

- docs/release-notes.md
https://github.com/coreos/butane/issues/355
Updating release-notes for new butane release
> update release-notes for new version

- docs/release-notes.md
We're going to try maintaining these incrementally as we work toward the next release, rather than building them from scratch at release time.
Also, backfill notes of historical signing key changes (xref https://github.com/coreos/repo-templates/pull/10).
> Add draft release notes for next release

- .github/workflows/go.yml
- go.mod
- vendor/github.com/coreos/go-json/go.mod
- vendor/github.com/spf13/pflag/go.mod
- vendor/gopkg.in/yaml.v3/go.mod
- vendor/modules.txt
> Bump minimum Go version to 1.17

- docs/config-fcos-v1_0.md
- docs/config-fcos-v1_1.md
- docs/config-fcos-v1_2.md
- docs/config-fcos-v1_3.md
- docs/config-fcos-v1_4.md
- docs/config-fcos-v1_5-exp.md
- docs/config-flatcar-v1_0.md
- docs/config-flatcar-v1_1-exp.md
- docs/config-openshift-v4_10.md
- docs/config-openshift-v4_11.md
- docs/config-openshift-v4_12-exp.md
- docs/config-openshift-v4_8.md
- docs/config-openshift-v4_9.md
- docs/config-rhcos-v0_1.md
- docs/release-notes.md
They specify the group that should be applied to the inode, not the primary group of the inode's owner.
> docs: clarify group fields in config specs

- .github/workflows/go.yml
- docs/release-notes.md
- test
Currently, the `test` script is not universally executable/skips large parts on non-Linux environments. With very few assumptions we can make it reasonably compatible with macOS and Windows (or at least offer a way for contributors to understand what they need to do to run it on those platforms successfully).
- use user supplied bash (e.g. modern, user installed Bash versions on macOS)
- skip doc checks only if necessary GNU utils aren't found
- macOS may have them prefixed with `g` (installed via Homebrew or MacPorts)
- Windows capable of running Bash scripts is most likely using Git Bash with
built in GNU utils such as csplit and head
- align formatting (4 vs. 8 spaces)
- prevent accidental word-splitting by quoting variables
- use shell redirects instead of `cat`
This is part of the …
> test: make test script universally executable

- .github/dependabot.yml
This should fix the missing `skip-notes` labels on Dependabot PRs.
> dependabot: permute the label order to flush Dependabot's config cache

- config/fcos/v1_5_exp/translate.go
Hash writes shouldn't fail, but Coverity doesn't know that.  Add a check and panic just to be sure.
> fcos/v1_5_exp: check return value when writing to hash

- config/common/errors.go
- config/config.go
- config/r4e/v1_0/schema.go
- config/r4e/v1_0/translate.go
- config/r4e/v1_0/translate_test.go
- config/r4e/v1_1_exp/schema.go
- config/r4e/v1_1_exp/translate.go
- config/r4e/v1_1_exp/translate_test.go
- docs/config-r4e-v1_0.md
- docs/config-r4e-v1_1-exp.md
- docs/release-notes.md
- docs/specs.md
This PR adds a new rhel-for-edge variant `r4e` targeting ignition 3.3.0 as well as an experimental variant targeting ignition 3.4.0.
Closes #396 
Checklist:
*Right now we won't support:*
> Add new r4e variant

- Dockerfile
https://github.com/coreos/fedora-coreos-tracker/issues/1223
> dockerfile: rebase to f37 from f36

- config/common/errors.go
- config/config.go
Now that the rhcos variant has been removed, attempting to use an rhcos config produces a non-actionable error:
Error translating config: No translator exists for variant rhcos with version 0.1.0
Add an explicit check and message:
Error translating config: rhcos variant has been removed; use openshift variant instead: https://coreos.github.io/butane/upgrading-openshift/
> Improve error on unsupported `rhcos` variant

- base/util/file.go
- docs/release-notes.md
Fixes https://github.com/coreos/butane/issues/119
> base/util: avoid error if storage.trees.local value equals to FilesDir

- base/v0_5_exp/schema.go
- config/openshift/v4_13_exp/translate_test.go
- docs/release-notes.md
They complicate the API without adding much value, and we use them inconsistently.  Followup to #53.
> base/v0_5_exp: remove `Option` wrapper types

- .github/workflows/go.yml
- docs/release-notes.md
- go.mod
> Bump minimum Go version to 1.18

- config/common/errors.go
- config/openshift/v4_13_exp/translate.go
- config/openshift/v4_13_exp/translate_test.go
- docs/config-openshift-v4_13-exp.md
- docs/release-notes.md
The MCO added support in https://github.com/openshift/machine-config-operator/pull/3539.
Awkwardly add `"password_hash" (4.13.0+)` to the existing error string. The alternative is creating a new error code for 4.13+, which would produce a cleaner error message, but that would break any callers programmatically checking for `ErrUserFieldSupport`.
cc @jkyros
> openshift/v4_13_exp: allow `passwd.users.password_hash`

- docs/config-openshift-v4_10.md
- docs/config-openshift-v4_11.md
- docs/config-openshift-v4_12.md
- docs/config-openshift-v4_13-exp.md
- docs/config-openshift-v4_8.md
- docs/config-openshift-v4_9.md
- docs/release-notes.md
OpenShift 4.13+ puts SSH keys in `.ssh/authorized_keys.d/ignition`.  Switch the 4.13 spec doc to that path.  For older spec docs we need to mention both paths, since Ignition will use the new path on 4.13+ even if an older Butane spec is used.
> docs/config-openshift-*: document location of SSH keys in RHEL 9

- docs/examples.md
- test
Add minimal examples to the butane documentation explaining how to use file references instead of inlining SSH keys and systemd units introduced with #179 .
Noticed this was missing while working on [coreos-docs#511](https://github.com/coreos/fedora-coreos-docs/issues/511).
> docs: add simple examples for SSH key & systemd file references (#179)

- docs/release-notes.md
- internal/main.go
- test
Add option to validate config without producing Ignition or MachineConfig output.
> internal: add `-c`/`--check` option to skip output

- .github/ISSUE_TEMPLATE/stabilize-checklist.md
Matches a similar checklist change in Ignition.
> templates/stabilize-checklist: note spec stabilization in release notes

- config/common/errors.go
- config/config.go
- docs/release-notes.md
Butane has two sites that want to include additional information in an error string.  Rather than requiring callers to string-match to detect these, define structs with the error details.
This should not be a breaking change.
> config: define error structs for errors that have context

- base/util/test.go
- base/v0_2/translate.go
- base/v0_2/translate_test.go
- base/v0_3/translate.go
- base/v0_3/translate_test.go
- base/v0_4/translate.go
- base/v0_4/translate_test.go
- base/v0_5/translate.go
- base/v0_5/translate_test.go
- base/v0_6_exp/translate.go
- base/v0_6_exp/translate_test.go
- docs/release-notes.md
Fix line/column reporting for `http_headers` errors.
> base: properly snake-case `http_headers` translation

- docs/config-fcos-v1_0.md
- docs/config-fcos-v1_1.md
- docs/config-fcos-v1_2.md
- docs/config-fcos-v1_3.md
- docs/config-fcos-v1_4.md
- docs/config-fcos-v1_5.md
- docs/config-fcos-v1_6-exp.md
- docs/config-openshift-v4_11.md
- docs/config-openshift-v4_12.md
- docs/config-openshift-v4_13.md
- docs/config-openshift-v4_14-exp.md
- docs/release-notes.md
- internal/doc/butane.yaml
It's available in current versions of FCOS and in OpenShift 4.11+.  Older FCOS releases don't support it, but Butane doesn't support _them_, so document it in every `fcos` spec.
> internal/doc: document `/dev/disk/by-id/coreos-boot-disk` symlink

- docs/development.md
Rendered docs [here](https://bgilbert.github.io/butane/development/#adding-sugar).
Release notes shouldn't be necessary here.
> docs/development: suggest implementing sugar via config merging

- config/common/errors.go
- config/fcos/v1_6_exp/schema.go
- config/fcos/v1_6_exp/translate.go
- config/fcos/v1_6_exp/validate.go
- docs/config-fcos-v1_6-exp.md
- docs/config-openshift-v4_15-exp.md
- docs/examples.md
- docs/release-notes.md
- internal/doc/butane.yaml
Hi,
I've closed the earlier pr 483 due to some errors. Here is the new PR.
As per the GitHub issue [https://github.com/coreos/butane/issues/453#issuecomment-1655441505]. The PR contains following conditional changes exclusively for s390x.
1. Added layout specific to s390x .
- > s390x-zfcp  s390x-eckd and s390x-virt .
2.   Added boot_device.luks.device specifically for s390x-zfcp s390x-eckd and forbidden for other arch including s390x-virt.
3.  The configuration will generate only with boot_device.luks and it fails if mirror boot_device.mirror  configuration is specified for s390x-eckd and s390x-zfcp .
> fcos: add s390x boot_device sugar

- docs/release-notes.md
- go.mod
> Bump minimum Go version to 1.20

- Dockerfile
- docs/release-notes.md
https://github.com/coreos/fedora-coreos-tracker/issues/1490
> Dockerfile: update to Fedora 39

- docs/config-openshift-v4_14.md
- internal/doc/butane.yaml
- internal/doc/main.go
docs: Fix openshift v4.14 generated docs
Fixes: https://github.com/coreos/butane/commit/186b8e8a7e2183b470f3edee967ca3da12761153
---
docs: Mark `grub` section as unsupported
See: https://github.com/coreos/butane/issues/515
---
internal/doc/butane: Fix whitespace
Fixes: 0d2fa0f spec/v1.6: Add support for boot_device sugar on s390x
> docs: Fix openshift v4.14 generated docs

- docs/release-notes.md
Update the release notes for Butane 0.20.0 as per the release checklist issue #512.
> docs/release-notes: update for release

- config/flatcar/v1_2_exp/translate.go
- config/flatcar/v1_2_exp/translate_test.go
- docs/config-flatcar-v1_2-exp.md
- docs/release-notes.md
This PR updates `flatcar/v1_2_exp` to reflect Flatcar can handle disk encryption with clevis, since [this commit](https://github.com/flatcar/scripts/pull/1560).
> flatcar/v1_2_exp: Add clevis support

- .github/ISSUE_TEMPLATE/release-checklist.md
- signing-ticket.sh
Created by [GitHub workflow](https://github.com/coreos/repo-templates/actions/workflows/sync.yml) ([source](https://github.com/coreos/repo-templates/blob/main/.github/workflows/sync.yml)).
Sync with coreos/repo-templates@f147a34ea797eff8193a3e3686b64d59594fffa2.
> Sync repo templates ⚙

- docs/release-notes.md
Update the release notes for Butane 0.21.0 as per the release checklist issue https://github.com/coreos/butane/issues/534.
> docs/release-notes.md: update for release Butane 0.21.0

- docs/release-notes.md
Write release notes in `docs/release-notes.md` for releasing Butane 0.22.0. See more:  https://github.com/coreos/butane/issues/546
> Release Butane 0.22.0

- docs/specs.md
The experimental specs are now using the 3.6.0-experimental ignition spec.
Fixes: https://github.com/coreos/butane/pull/566
> docs/specs: Fix experimental spec mapping

- docs/release-notes.md
Write release notes in docs/release-notes.md for releasing Butane 0.23.0. See more: https://github.com/coreos/butane/issues/550
> Release Butane 0.23.0

- docs/getting-started.md
See https://github.com/coreos/butane/issues/573.
> Docs - Getting Started: Fix examples of using container images

- docs/specs.md
Update the table header listing the correspondance between Butane and Ignition specifications to clarify that we are not speaking about Butane releases / versions here (i.e. the application) but specification versions instead.
> docs/specs: Clarify that those are Butane spec versions

- .github/ISSUE_TEMPLATE/stabilize-checklist.md
With the latest changes to github's issue templates you must have a yaml matter header for the issue template to function.
> issue_template/stabilize-checklist: add yaml matter header

- Dockerfile
Switch the builder stage from `registry.fedoraproject.org` to `quay.io/fedora/fedora:42` to align with common usage in container build workflows.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1851
> Dockerfile: use quay.io as source for Fedora base image

- docs/release-notes.md
Fixes: 9c96382 docs: note bugfix for failure when LUKS method is missing but device is specified
> docs: Move new bug fix entry to unreleased version

- base/v0_2/translate.go
- base/v0_2/util.go
- base/v0_2/validate.go
- base/v0_2/validate_test.go
- base/v0_3/translate.go
- base/v0_3/util.go
- base/v0_3/validate.go
- base/v0_3/validate_test.go
- base/v0_4/translate.go
- base/v0_4/util.go
- base/v0_4/validate.go
- base/v0_4/validate_test.go
- base/v0_5/translate.go
- base/v0_5/util.go
- base/v0_5/validate.go
- base/v0_5/validate_test.go
- base/v0_6/translate.go
- base/v0_6/util.go
- base/v0_6/validate.go
- base/v0_6/validate_test.go
- base/v0_7_exp/translate.go
- base/v0_7_exp/util.go
- base/v0_7_exp/validate.go
- base/v0_7_exp/validate_test.go
- config/common/errors.go
- docs/examples.md
- docs/release-notes.md
- test
> feat: add validation to merged local/inline configs
