coreos/butane

.github/ISSUE_TEMPLATE/release-checklist.md, build, build_releases, docs/development.md, tag_release.sh
Add release tagging/building scripts as well as a checklist.
=> Add release tooling

config/config.go, config/v1_0/fcos.go, docs/development.md, docs/getting-started.md, go.mod, internal/main.go
Fix all the import paths and docs to use github.com/coreos/fcct instead
of github.com/ajeddeloh/fcct.
=> *: move to coreos org

docs/examples.md
=> docs/examples: fix link to config spec

build, build_releases, internal/main.go, internal/version/version.go
Fixes https://github.com/coreos/fcct/issues/16
=> main: add --version flag

Dockerfile
Add a dockerfile for building release containers.
=> Dockerfile: add dockerfile for releases

.travis.yml, test
Extract and try all the examples in the docs as part of the test process
to ensure we don't include invalid examples.
Fixes https://github.com/coreos/fcct/issues/24
Fixes https://github.com/coreos/fcct/issues/23
=> test: add checking for examples in docs, travis

go.mod, go.sum
This includes a validation fix that file and directory paths.
=> go.mod: bump ignition to 2.0.1

docs/configuration-v1_0.md
password_hashes should be hashes not encrypted
=> [docs] passwords are hashed not encrypted

.github/ISSUE_TEMPLATE/release-checklist.md
=> release-checklist: add instructions for updating Fedora RPM

base/v0_2_exp/translate.go, base/v0_2_exp/translate_test.go
Use base64 encoding if the result is smaller than URL escaping.  If the user didn't already enable compression, and base64-encoded gzip is smaller than the alternatives, use that instead.
All versions of Ignition that support spec 3.1.0 should support compression in data URLs.  Older versions don't, so limit this to base 0.2.
Depends on https://github.com/coreos/fcct/pull/99.  Fixes https://github.com/coreos/fcct/issues/94.
=> base/v0_2: auto-select encoding for inline/local file contents

docs/configuration-v1_0.md, docs/configuration-v1_1-exp.md
Fixes #103 (not mergeable until https://github.com/coreos/fcct/pull/102 gets merged)
=> [docs]: Add CA bundle information

NEWS, docs/development.md, docs/migrating-configs.md, test
Add migration notes for spec 1.1.0, spec bump instructions, and update NEWS.
=> Docs updates for 0.6.0

docs/configuration-v1_0.md, docs/configuration-v1_1.md, docs/configuration-v1_2-exp.md, docs/development.md, docs/examples.md, docs/migrating-configs.md, docs/specs.md
Preview: https://travier.github.io/fcct/
=> docs: Re-order specs, add ToC, rename Migrating page

docs/examples.md
IMO basically every oneshot unit should have this, because it
really matters as soon as your units start having dependencies
on one another, and that will likely happen as soon as
someone starts doing anything that's not printing "hello world".
=> docs/example: Add RemainAfterExit=yes

docs/configuration-v1_2.md, docs/configuration-v1_3-exp.md
Fixes https://github.com/coreos/fcct/issues/165.
=> docs: add luks wipe_volume field

base/util/test.go, base/v0_1/translate_test.go, base/v0_2/translate_test.go, base/v0_3/translate_test.go, base/v0_4_exp/translate_test.go, config/fcos/v1_0/translate.go, config/fcos/v1_1/translate.go, config/fcos/v1_2/translate.go, config/fcos/v1_3_exp/translate.go, test, translate/set.go, translate/util.go
=> Miscellaneous cleanups

docs/config-fcos-v1_2.md, docs/config-fcos-v1_3.md, docs/config-fcos-v1_4-exp.md
=> docs: fix indentation level for storage.luks

docs/config-fcos-v1_2.md, docs/config-fcos-v1_3.md, docs/config-fcos-v1_4-exp.md, docs/config-rhcos-v0_1.md, docs/config-rhcos-v0_2-exp.md
This is supported in `fcos` 1.2.0+ configs and all `rhcos` configs.
Closes: #201
=> docs: add `resize` key

docs/config-fcos-v1_0.md, docs/config-fcos-v1_1.md, docs/config-fcos-v1_2.md, docs/config-fcos-v1_3.md, docs/config-fcos-v1_4-exp.md, docs/config-rhcos-v0_1.md, docs/config-rhcos-v0_2-exp.md
Port of https://github.com/coreos/ignition/pull/1169.
=> docs/config-*: document wipe_filesystem default

.github/ISSUE_TEMPLATE/release-checklist.md, .github/workflows/container.yml, .github/workflows/go.yml, docs/_config.yml
We're about to rename the repository (#167) and we might as well rename the main branch at the same time.
=> Rename master branch to main

go.mod, go.sum, vendor/github.com/coreos/vcontext/path/path.go, vendor/github.com/coreos/vcontext/report/report.go, vendor/github.com/coreos/vcontext/validate/validate.go, vendor/modules.txt
https://github.com/coreos/vcontext/pull/14
=> go.mod: update vcontext for report path fix

base/v0_4_exp/schema.go, base/v0_4_exp/translate.go, docs/config-fcos-v1_4-exp.md, docs/config-openshift-v4_9-exp.md, go.mod, go.sum, vendor/github.com/coreos/ignition/v2/config/util/reflection.go, vendor/github.com/coreos/ignition/v2/config/v3_3_experimental/types/kargs.go, vendor/github.com/coreos/ignition/v2/config/v3_3_experimental/types/schema.go, vendor/modules.txt
This is a rough draft to add FCC sugar for specifying kargs. A few changes are expected  based on how [this](https://github.com/coreos/ignition/pull/1178) PR evolves over a period time.
=> Add FCC sugar for specifying kernel arguments

config/fcos/v1_3/translate.go, config/fcos/v1_4_exp/translate.go
It hasn't switched yet, but will soon.
=> fcos/*: rename cosa's master branch to main

docs/config-fcos-v1_2.md, docs/config-fcos-v1_3.md, docs/config-fcos-v1_4-exp.md, docs/config-openshift-v4_8.md, docs/config-openshift-v4_9-exp.md, docs/config-rhcos-v0_1.md
and the corresponding default in `boot_device.luks.threshold`.
xref https://github.com/coreos/ignition/pull/1239
=> docs/config*: document `storage.luks.clevis.threshold` default

config/fcos/v1_3/translate.go, config/fcos/v1_4/translate.go, config/fcos/v1_5_exp/translate.go
Addresses: https://github.com/coreos/butane/pull/279#discussion_r747239076
=> config/fcos: fix up conditional while warn about the partition number

docs/getting-started.md
Follow-up to https://github.com/coreos/butane/pull/294
=> docs: Add wrapper script for container installs

docs/config-fcos-v1_2.md, docs/config-fcos-v1_3.md, docs/config-fcos-v1_4.md, docs/config-fcos-v1_5-exp.md, docs/config-rhcos-v0_1.md
Add gs support in doc to fit code functionalities
=> docs: add gs URL support to specs

base/util/test.go, base/v0_1/translate_test.go, base/v0_2/translate_test.go, base/v0_2/validate_test.go, base/v0_3/translate_test.go, base/v0_4/translate_test.go, base/v0_5_exp/translate_test.go, config/fcos/v1_3/translate_test.go, config/fcos/v1_4/translate_test.go, config/fcos/v1_5_exp/translate_test.go, config/openshift/v4_10/translate_test.go, config/openshift/v4_11_exp/translate_test.go, config/openshift/v4_8/translate_test.go, config/openshift/v4_9/translate_test.go
Small followups to #311.
cc @Okeanos
=> More cleanup

.github/ISSUE_TEMPLATE/release-checklist.md
xref https://github.com/coreos/ignition/pull/1320#discussion_r812170624
=> templates/release-checklist: spell out the RHCOS packaging steps

.github/ISSUE_TEMPLATE/release-checklist.md
Making appropriate changes which are shared from ignition release https://github.com/coreos/ignition/issues/1353
=> release-checklist.md: updates and improvements

docs/config-fcos-v1_2.md, docs/config-fcos-v1_3.md, docs/config-fcos-v1_4.md, docs/config-fcos-v1_5-exp.md, docs/config-flatcar-v1_0.md, docs/config-flatcar-v1_1-exp.md, docs/config-rhcos-v0_1.md, docs/release-notes.md
Initially added in https://github.com/coreos/butane/pull/141
=> docs: document `users`/`groups` `should_exist` fields

.github/workflows/container-rebuild.yml, .github/workflows/container.yml, docs/release-notes.md
Created by [GitHub workflow](https://github.com/coreos/repo-templates/actions/workflows/sync.yml) ([source](https://github.com/coreos/repo-templates/blob/main/.github/workflows/sync.yml)).
Sync with coreos/repo-templates@30f9d7fc373a10994edd7dc3e44bfe54e72f0719.
=> Sync repo templates ⚙

.github/ISSUE_TEMPLATE/stabilize-checklist.md, docs/development.md
Move text and add checkboxes.  No substantive changes.
=> templates: move spec bump checklist to an issue template

config/common/errors.go, config/fcos/v1_6_exp/validate.go, config/fcos/v1_6_exp/validate_test.go, docs/release-notes.md
=> fcos/v1_6_exp: Fail if mountpoint path is forbidden by FCOS

docs/release-notes.md
https://github.com/coreos/butane/issues/490
=> docs/release-notes: update for release

docs/examples.md
Related to: https://github.com/coreos/fedora-coreos-docs/pull/630
=> Docs: Increase the size of a mirrored root partition

Dockerfile
https://github.com/coreos/fedora-coreos-tracker/issues/1674
=> Dockerfile: update to Fedora 40

Dockerfile, docs/release-notes.md
see: https://github.com/coreos/fedora-coreos-tracker/issues/1695
=> Dockerfile: update to Fedora 41

Dockerfile
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1851
=> Dockerfile: update to Fedora 42

.github/workflows/tmt-tests.yml, Dockerfile, docs/release-notes.md, tests/core/core.fmf, tests/main.fmf, tests/smoke/main.fmf, tests/smoke/test.sh, tests/tmt/plans/main.fmf, tests/tmt/plans/smoke.fmf
The github workflow to execute TMT butane gating tests is added.
=> Add github workflow for butane gating test

.github/workflows/issue-eval.yml
Add the issue-eval template to start having Issues be evaluated on creation. 
This might be removed later as we are testing to see how it performs.
=> issue-eval: add AI workflow to evaluate new issues

docs/release-notes.md
Release docs update for v0.25.0 release
=> docs/release-notes: update for release v0.25.1
